# Generated by Django 5.1 on 2024-08-27 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurants',
            old_name='category',
            new_name='adress',
        ),
        migrations.RemoveField(
            model_name='restaurants',
            name='author',
        ),
        migrations.AddField(
            model_name='restaurants',
            name='small_description',
            field=models.TextField(blank=True),
        ),
    ]
