# Generated by Django 5.1 on 2024-08-27 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartments',
            old_name='category',
            new_name='adress',
        ),
        migrations.RemoveField(
            model_name='apartments',
            name='author',
        ),
        migrations.AddField(
            model_name='apartments',
            name='small_description',
            field=models.TextField(blank=True),
        ),
    ]
