# Generated by Django 5.1 on 2024-10-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0003_apartments_adress_en_apartments_adress_mk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartments',
            name='place',
            field=models.CharField(default='Gevgelija', max_length=100),
        ),
    ]
