# Generated by Django 5.1 on 2024-10-07 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogs_description_delete_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='is_published',
        ),
    ]
