# Generated by Django 5.1 on 2024-10-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0002_rename_category_coffee_adress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='adress_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='coffee',
            name='adress_mk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='coffee',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coffee',
            name='description_mk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coffee',
            name='small_description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coffee',
            name='small_description_mk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coffee',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='coffee',
            name='title_mk',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
